name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: admin_docker
          POSTGRES_DB: testDB
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: inspect containers
        run: |
          docker ps
      - name: Query database
        run: psql -h localhost -d testDB -U admin_docker -c 'SELECT 1;'
        env:
          PGPASSWORD: postgres
      - name: Run migrations
        run: |
          psql -f scripts/firstMigration.sql postgres://admin_docker:postgres@localhost:5432/testDB
          psql -f scripts/Populate_db.sql postgres://admin_docker:postgres@localhost:5432/testDB

      
